const state={data:null,filter:'全部',query:'',read:new Set(JSON.parse(localStorage.getItem('cs-read')||'[]')),deleted:new Set(JSON.parse(localStorage.getItem('cs-deleted')||'[]'))};
const topicLabels={'organic':'有机电催化 CO₂','gde':'GDE / Micro-CT','analysis':'电化学分析','recommended':'为你推荐'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){localStorage.setItem('cs-read',JSON.stringify([...state.read]));localStorage.setItem('cs-deleted',JSON.stringify([...state.deleted]));}
function card(p,i){const read=state.read.has(p.id);return `<article class="paper ${read?'read':''}" data-id="${esc(p.id)}"><div class="paper-index">${String(i+1).padStart(2,'0')}</div><div><div class="paper-meta"><b>${esc(topicLabels[p.topic]||p.topic)}</b> • ${esc(p.badge||'最新研究')} • ${esc(p.read_minutes||10)} min</div><h3><a href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.title)} ↗</a></h3><div class="journal">${esc(p.journal)} ${esc(p.year)} <span>${p.impact_factor?`IF ${esc(p.impact_factor)}`:'IF —'} · ${esc(p.quartile||'Q —')}</span></div><p class="paper-summary">${esc(p.summary_zh||p.abstract||'暂无摘要')}</p><div class="why"><b>为什么与你相关</b><br>${esc(p.relevance_reason||'与当前追踪主题高度匹配。')}</div><div class="tags">${(p.tags||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="actions"><button class="text-btn why-btn">查看研究解读 →</button><a class="text-btn" href="${esc(p.url)}" target="_blank" rel="noopener">打开原文网页 ↗</a><button class="text-btn read-btn">${read?'↶ 标记未读':'✓ 标记已读'}</button><button class="text-btn delete-btn">删除</button></div></div><div class="score"><strong>${esc(p.score||80)}</strong><span>相关度</span></div></article>`}
function filtered(papers){return papers.filter(p=>!state.deleted.has(p.id)).filter(p=>state.filter==='全部'||(state.filter==='为你推荐'?p.score>=88:topicLabels[p.topic]===state.filter)).filter(p=>{if(!state.query)return true;const q=state.query.toLowerCase();return [p.title,p.summary_zh,p.journal,...(p.tags||[])].join(' ').toLowerCase().includes(q)})}
function render(){const d=state.data;const current=filtered(d.papers.filter(p=>!p.archive));const archive=filtered(d.papers.filter(p=>p.archive));document.getElementById('paperList').innerHTML=current.map(card).join('')||'<p class="paper-summary">没有匹配的文献。</p>';document.getElementById('archiveList').innerHTML=archive.map(card).join('')||'<p class="paper-summary">暂无历史文献。</p>';document.getElementById('archiveCount').textContent=d.papers.filter(p=>p.archive&&!state.deleted.has(p.id)).length;document.getElementById('readCount').textContent=d.papers.filter(p=>p.archive&&state.read.has(p.id)&&!state.deleted.has(p.id)).length;bindCards();}
function bindCards(){document.querySelectorAll('.paper').forEach(el=>{const id=el.dataset.id;el.querySelector('.why-btn').onclick=()=>el.classList.toggle('expanded');el.querySelector('.read-btn').onclick=()=>{state.read.has(id)?state.read.delete(id):state.read.add(id);persist();render()};el.querySelector('.delete-btn').onclick=()=>{state.deleted.add(id);persist();render()}})}
async function init(){const r=await fetch('data/papers.json',{cache:'no-store'});state.data=await r.json();const d=state.data;document.getElementById('briefDate').textContent=`${d.brief_date||''} 研究简报`;const today=d.papers.filter(p=>!p.archive);document.getElementById('statToday').textContent=today.length;document.getElementById('statHigh').textContent=today.filter(p=>p.score>=88).length;document.getElementById('statMethods').textContent=today.filter(p=>p.topic==='analysis').length;document.getElementById('matchScore').textContent=(d.match_score||96)+'%';document.querySelector('.meter span').style.width=(d.match_score||96)+'%';document.getElementById('lastUpdated').textContent='最后更新 '+(d.last_updated||'—');const names=['全部','有机电催化 CO₂','GDE / Micro-CT','电化学分析','为你推荐'];document.getElementById('filters').innerHTML=names.map(n=>`<button class="filter ${n==='全部'?'active':''}">${n}${n==='全部'?today.length:''}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.filter=b.textContent.replace(/\d+$/,'');document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});document.getElementById('topicTracker').innerHTML=(d.trackers||[]).map(t=>`<div class="topic-row"><span>${esc(t.name)}</span><span>${esc(t.rate)}</span></div>`).join('');render();}
document.getElementById('searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});document.getElementById('openSearch').onclick=()=>document.getElementById('searchInput').focus();document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('searchInput').focus()}});document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsDialog').showModal();init().catch(err=>{console.error(err);document.getElementById('paperList').innerHTML='<p class="paper-summary">数据加载失败。请通过本地服务器或 GitHub Pages 打开网页。</p>'});
